name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.0.3

      - name: Deno version
        run: deno --version

      - name: Format check
        run: deno fmt --check

      - name: Tests
        run: deno test
